

artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/gowtham-dd/Datasets/raw/main/QABOT.zip
  local_data_file: artifacts/data_ingestion/QABOT.zip
  unzip_dir: artifacts/data_ingestion
